### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [dkamm/deepcoder#10]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by flowlord** [comment]
sorry ? I do not manage this project

**Comment by dkamm** [comment]
@suprafun To be honest, I hadn't thought about a license for this project.  I'm thinking either MIT or Public Domain.  Do you have any recommendation?

**Comment by flowlord** [comment]
Sorry I do not know anything in license done research on google.

**Comment by dkamm** [comment]
@lolokoko28 awesome! I made it MIT license. Good luck with your project!
