### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by sangeeta0201** [dkamm/deepcoder#7]
Hi, 

You have changed options in gen_program.py but your readme is not updated. Can you please update it.

I am getting following errro-
gen-programs.py: error: unrecognized arguments: --max_nb_prog 100000 --out deepcoder/dataset/programs_small.txt

**Comment by dkamm** [comment]
Hi sangeeta,

Thanks for opening this issue! I have updated the README and cleaned up some of the code in the process. Feel free to reopen this ticket if you run into any problems
